[package]
name = "restful-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
serde = { version = "1.0.209", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
